### ISSUE TITLE
Recipe class / objects and formatting / storage

### ISSUE THREAD

**Issue by fosesqno** [nmsu-cs/project-penguin-byte-java-squad#10]
Creating a Recipe object class that will have a recipe constructor, and certain methods in order to interact or obtain a cleaner way to hold recipe data.
One function will intake a ResultSet object from the java.sql.* import and it will return an ArrayList<recipe> object that will have all the recipes returned by a certain query. 
Within the recipe object will be these attributes:
int id,
String title,
String[] ingredients,
String[] instructions,
String link,
String[] NER
The column "source" will be omitted, as it is not essential to our dataset and is consistent throughout the table as "Gathered".
there will be getter and setter methods for a specific recipe being held.

**Comment by DouglasJack** [comment]
Completed last week by andrew.
