### ISSUE TITLE
Sharing information to the client

### ISSUE THREAD

**Issue by DouglasJack** [nmsu-cs/project-penguin-byte-java-squad#2]
How do we have clients download this information? We can compose data to the client, but then how do we spin up a MySQL server when the application is executed to service the data?

**Comment by jyanez04** [comment]
@DouglasJack After talking with Dr. Lopez, she took the group to talk with Mike about hosting our database on one of the machines in SH118. Mike said he could allow us to use a VM he would create so we could host the database on that VM instead. This way, users won't need to download an SQL server to their machine. The team is currently waiting on the status of the VM creation at the moment.

**Comment by DouglasJack** [comment]
Solved, Remote DB and JDBC connection.
