### ISSUE TITLE
Getting included recipes

### ISSUE THREAD

**Issue by DouglasJack** [nmsu-cs/project-penguin-byte-java-squad#3]
How do we write a query that returns ONLY the recipes that have ALL of the ingredients specified in our ingredient list?

**Comment by pattyl11** [comment]
I'm expecting to see a lot more issues in your issues list. @DouglasJack - you can @ members of your team to make sure they see your messaged. @jyanez04 @BRDY-SCAG @fosesqno.

**Comment by DouglasJack** [comment]
#10 Complete.
