### ISSUE TITLE
Creating and storing an Ingredient/Shopping List

### ISSUE THREAD

**Issue by jyanez04** [nmsu-cs/project-penguin-byte-java-squad#4]
The product needs a way to allow the user to either import their own shopping list or create one within the app. This may be done by presenting the user with that option somewhere inside a side menu or something. @DouglasJack @BRDY-SCAG @fosesqno

**Comment by DouglasJack** [comment]
Jacob has added this feature in as a secondary importation window, allowing the import of .txt documents. This then scans and writes data to an ArrayList<String> for future use in the #15. This issue took some completion time, and is now fully implemented.
