### ISSUE TITLE
Difficulty indication and filtering on it

### ISSUE THREAD

**Issue by jyanez04** [nmsu-cs/project-penguin-byte-java-squad#6]
The product needs a way to indicate the difficulty of recipes so it may be easier for beginning cooks to find recipes suited to their experience in the kitchen. @DouglasJack @fosesqno @BRDY-SCAG

**Comment by DouglasJack** [comment]
I have added this, however I've also removed it. We did not find it to be very useful to a user as it assumes ingredient length equals difficulty.
